# Generated by Django 3.2.8 on 2021-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney_info',
            name='Category',
            field=models.CharField(choices=[('Work', 'Work'), ('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('Passive income', 'Passive income')], default='Food', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('Progammer', 'Programmer'), ('Teacher', 'Teacher'), ('Employee', 'Employee'), ('Business', 'Business'), ('Student', 'Student'), ('Other', 'Other')], max_length=10),
        ),
    ]
